### ISSUE TITLE
jsonMapper is mentioned as a param but not used

### ISSUE THREAD

**Issue by ek08** [spdx/tools-java#10]
https://github.com/spdx/tools-java/blob/8846a186888ea55e07dc892b276a0537d2f26a21/src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java#L101

For the method toArrayPropertySchema(OntClass ontClass, int min) of https://github.com/spdx/tools-java/tree/master/src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java  
https://github.com/spdx/tools-java/blob/8846a186888ea55e07dc892b276a0537d2f26a21/src/main/java/org/spdx/tools/schema/OwlToJsonSchema.java#L105
jsonMapper is mentioned as a param but it is not used as a parameter in the function

**Comment by goneall** [comment]
Looks like the JavaDoc param should just be removed - @ek08 feel free to submit a PR

**Comment by goneall** [comment]
Resolved with PR #11
