### ISSUE TITLE
LicenseRef Validation Issues?

### ISSUE THREAD

**Issue by sgeary01** [spdx/tools-java#106]
I am attempting to validate and seem to be having issues based on my use of LicenseRef which has worked successfully in the past using tools-java-1.1.1-jar-with-dependencies.jar

I started seeing the issues with version 1.1.2 which continues in 1.1.4

i.e.

```
This SPDX Document is not valid due to:
        Package at line 54 invalid: License not found for LicenseRef-GPL-2.0-with-classpath-exception in checker-qual
        Package at line 130 invalid: License not found for LicenseRef-GNU-Library-Lesser-General-Public-License in jboss-logging
        License not found for LicenseRef-GNU-Library-Lesser-General-Public-License in jboss-logging
        License not found for LicenseRef-GPL-2.0-with-classpath-exception in checker-qual

```
I also tried with a a simple numerical index with the same error. 

These seem valid per the spec and in looking at the repo change logs I am not seeing anything that jumps out at me as to what may have changed.

Any guidance?

Thanks!

**Comment by goneall** [comment]
@sgeary01 - It looks like this should be valid.  If you can you upload an SPDX document to reproduce the issue, I'll take a look.

**Comment by sgeary01** [comment]
@goneall Please find the example attached
[licenseRef.zip](https://github.com/spdx/tools-java/files/10578216/licenseRef.zip)
Thanks!

**Comment by maxhbr** [comment]
Hey @sgeary01,

your SPDX file contains the refs, but without the listing of extracted texts in the end of the document.
```
$ grep LicenseRef- licenseRef.spdx
62:PackageLicenseDeclared: (LicenseRef-GPL-2.0-with-classpath-exception OR MIT)
138:PackageLicenseDeclared: (Apache-2.0 OR LGPL-2.1-only OR LicenseRef-GNU-Library-Lesser-General-Public-License)
```

So, it looks correct that the tools complain about missing license information. And this validation was missing previously in 1.1.2.

So your tool `Revenera Code Insight` needs to add [extractedLicenseText and more necessary metadata](https://spdx.github.io/spdx-spec/v2.2.2/other-licensing-information-detected/)  for each LicenseRef.

**Comment by sgeary01** [comment]
Thanks!  I missed that in the spec so will update accordingly!
