### ISSUE TITLE
Running SpdxConverterTest.java gives error

### ISSUE THREAD

**Issue by ek08** [spdx/tools-java#13]
When i run the SpdxConveterTest.java file it gives the error shown below 
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
There is a log4j2.xml file still is not able to get processed

**Comment by rnjudge** [comment]
I also see this error when I run the Validate test but I am still able to run the tool. So it seems like more of warning and less of an actual error?

**Comment by goneall** [comment]
I've noticed this error as well.  Haven't been able to figure out the cause or solution - any help would be appreciated :)

**Comment by ek08** [comment]
> I also see this error when I run the Verify test but I am still able to run the tool. So it seems like more of warning and less of an actual error?

Yup it is an warning but whenever you will create a PR the build with maven will fail
