### ISSUE TITLE
Licenses and internet access

### ISSUE THREAD

**Issue by dstutz** [spdx/tools-java#132]
When I create an SPDX document using the library, by default, I see it going out to the internet for license information.  If I don't have internet access it quickly gives up and outputs the following error message:
```
[SEVERE] Unable to access the most current listed licenses from https://spdx.org/licenses - using locally cached licenses: I/O error reading license TOC 
```

Is there a way to just completely disable it from checking the internet? Can I supply my own copy of the licenses.json file, which I already have for the purposes of creating CycloneDX files using SPDX license IDs.  I assume each new version of the library ships with the current license data so as long as the library is updated the license data would be for offline usage.

**Comment by goneall** [comment]
> Is there a way to just completely disable it from checking the internet?

Yes - there are actually 2 ways to disable the checking of the internet:
- Set a system property `SPDXParser.OnlyUseLocalLicenses=true` (e.g. `java -DSPDXParser.OnlyUseLocalLicenses=true ...`
- Set the `OnlyUseLocalLicenses=true` in the [SPDX Java Library licenses properties file](https://github.com/spdx/Spdx-Java-Library/blob/master/resources/licenses.properties).

Suggest the former as it can be done on the command line and doesn't require any repackaging of the Jar file.

**Comment by goneall** [comment]
BTW - The code that implements this is here: https://github.com/spdx/Spdx-Java-Library/blob/e718e7ea913b5df92abc30b21d561874b354582f/src/main/java/org/spdx/library/model/license/ListedLicenses.java#L65

**Comment by dstutz** [comment]
Awesome, thank you very much.  That's perfect.

**Comment by dstutz** [comment]
Awesome, thank you very much. That's perfect.
