### ISSUE TITLE
Blank version string validates

### ISSUE THREAD

**Issue by rnjudge** [spdx/tools-java#133]
I'm not sure if this is an issue or an oversight in the spec but I have an SBOM with a blank version string that properly validates. Is this proper behavior? I have attached the file for reference (with appended .txt since GH doesn't allow uploading json files)

[tern_tern-tools_2aab4fb3af706feefe7137f442951108f541b058.json.txt](https://github.com/spdx/tools-java/files/12089010/tern_tern-tools_2aab4fb3af706feefe7137f442951108f541b058.json.txt)

**Comment by goneall** [comment]
In the spec, it is optional and just defined as a string, so technically an empty string would be valid - so I think it would be considered proper behavior.

**Comment by rnjudge** [comment]
Hmm, ok. Perhaps an improvement for the spec. A blank string isn't very useful to anyone.

**Comment by goneall** [comment]
> Perhaps an improvement for the spec. A blank string isn't very useful to anyone.

@rnjudge 
Agree.  We had an interesting discussion on the tech call today on parsing version strings as well.
