### ISSUE TITLE
how to get SPDXpackages form spdxDocument

### ISSUE THREAD

**Issue by lunbin** [spdx/tools-java#137]
i have got spdxDocument  by deserializeDocument function， like this:

```java
  spdxDocument = SpdxToolsHelper.deserializeDocument(new File(file), SpdxToolsHelper.SerFileType.JSON);

```
the file like [this](https://github.com/spdx/tools-java/blob/master/testResources/SPDXJSONExample-v2.3.spdx.json)

but spdxDocument  do not have getPackages() ,like this function , how can i get the package list use tools-java?

please help me. thank you!

**Comment by lunbin** [comment]
@kemitchell @sschuberth  @vargenau

**Comment by goneall** [comment]
@lunbin - There are a couple of approaches depending on what you are trying to accomplish with the packages.

If you just want to get all the packages described in the document independent of how that package is referenced or used, you can use the [SpdxModelFactory.getelements()](https://github.com/spdx/Spdx-Java-Library/blob/4666b452a5d09af9847ee3045fe4ea6b946ed432/src/main/java/org/spdx/library/model/SpdxModelFactory.java#L248) method.  You can find an example of this in the tag/value parser: https://github.com/spdx/spdx-java-tagvalue-store/blob/23dcbe43993f90cd0569b47d799a02d390e98bf8/src/main/java/org/spdx/tag/CommonCode.java#L235

If you want to find the packages that are described directly or indirectly by the SPDX Document, you can traverse the graph of relationships starting with the [documentDescribes](https://github.com/spdx/Spdx-Java-Library/blob/4666b452a5d09af9847ee3045fe4ea6b946ed432/src/main/java/org/spdx/library/model/SpdxDocument.java#L94) collection which is the root of the relationships graph for the document.
