### ISSUE TITLE
Warning "No SLF4J providers were found"

### ISSUE THREAD

**Issue by vargenau** [spdx/tools-java#153]
How to get rid of the following warning:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```

tools-java release 1.1.8

**Comment by goneall** [comment]
I wish I knew - @pmonks do you have any ideas?  Perhaps something we should configure in the main part of the app?

note related #43

**Comment by pmonks** [comment]
@vargenau this probably means you don't have an SLF4J implementation JAR in your classpath. The reason Spdx-Java-Library doesn't provide one is that there are several choices that are suited for different scenarios/preferences, and it's inappropriate for a library to make that implementation decision on behalf of all downstream consumers.

The solution is to pick one of the [SLF4J implementations](https://www.slf4j.org/manual.html#swapping) and add it to your classpath (perhaps via a build file, if you're using a build tool e.g. `pom.xml` if you're using Maven).

**Comment by vargenau** [comment]
@pmonks 
Thank you for your explanations.

Previously my shell-script was:
```
#!/bin/csh -f
java -jar /Users/mvargena/bin/tools-java/tools-java-1.1.8-jar-with-dependencies.jar Verify $*
```

I have updated it to:
```
#!/bin/csh -f
java -classpath "/Users/mvargena/Java/slf4j-api-2.0.11.jar:/Users/mvargena/Java/slf4j-nop-2.0.11.jar" -jar /Users/mvargena/bin/tools-java/tools-java-1.1.8-jar-with-dependencies.jar Verify $*
```
but I still get the same warnings.

What am I doing wrong?

**Comment by pmonks** [comment]
@vargenau do all those files exist in those locations? Also, IIRC `Spdx-Java-Library` has more dependencies than that, so you'll likely hit further class loading issues until you have the entire transitive dependency graph expressed on the command line.

I'd encourage you to consider using a Maven-based build tool (Maven, Gradle, etc.) instead of trying to manually manage Java dependencies like this - the approach you're taking is quite brittle and error prone.

**Comment by vargenau** [comment]
Hi @pmonks 
Yes, these files exist and are readable.

I even removed the Apple quarantine flag (it's a Mac):
```
xattr -d com.apple.quarantine *.jar
```

But that does not help.

Anyway, I can live with these warnings.

**Comment by le-jhe** [comment]
I have a proposed fix in the pull request above. Can you review it ?

**Comment by vargenau** [comment]
@goneall 
Hi Gary,
Could you please check if this fixes the issue?
Thank you

**Comment by pmonks** [comment]
> @pmonks - any thoughts on whether we should merge in PR #158 ?

@goneall added a comment in the PR.  I have a vague recollection that it _might_ be possible to achieve both goals (dependency included in uberjar, but completely missing in library jar & pom) via some Maven magic.
