### ISSUE TITLE
Support to validate SPDX JSON documents?

### ISSUE THREAD

**Issue by rnjudge** [spdx/tools-java#3]
I don't see support to validate SPDX JSON documents with the current tooling. Is there tooling support available for this currently that I am overlooking or is this coming in the future?

**Comment by goneall** [comment]
@rnjudge The [Verify class](https://github.com/spdx/tools-java/blob/master/src/main/java/org/spdx/tools/Verify.java) should support JSON documents.  Let me know if you're having any issues verifying the JSON documents.

**Comment by rnjudge** [comment]
Hi @goneall I pulled the jar file from [here](https://github.com/spdx/tools/releases/tag/v2.2.4) and ran it on my Mac. I used the command
`java -jar spdx-tools-2.2.4-jar-with-dependencies.jar Verify spdx_example.json`
but got the following error:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
16:48:51.726 [main] ERROR org.apache.jena.riot - [line: 1, col: 1 ] Content is not allowed in prolog.
Unable to parse the file: File ../Desktop/output.json is not a recognized RDF/XML or tag/value format. While verifying for Tag/Value format: The SPDX Document Namespace must be set before other SPDX document properties are set.. While verifying for RDF/XML format: [line: 1, col: 1 ] Content is not allowed in prolog.
```

The error doesn't seem to be unique to my document, however, as I ran the [example](https://raw.githubusercontent.com/spdx/spdx-spec/master/examples/SPDXJSONExample-v2.2.spdx.json) SPDX JSON document through it as well and got the same error. I attached my test document below for reference.

[output-spdx-json.txt](https://github.com/spdx/tools-java/files/5790123/output-spdx-json.txt) (Converted from json to txt since GitHub doesn't support json file uploads)

Any insight you have as to whether or not I am running the validation check right would be appreciated :)

**Comment by goneall** [comment]
@rnjudge It looks like you are running the old version of the SPDX tools which does not support JSON.

Download the new version from https://bintray.com/spdx/spdx-tools/download_file?file_path=org%2Fspdx%2Ftools-java%2F0.0.4%2Ftools-java-0.0.4-jar-with-dependencies.jar

**Comment by rnjudge** [comment]
Thanks Gary! Now when I try to `Verify` with both the example JSON document from the SPDX website and my own document I get the following, even though they both have a `documentNamespace` field present.

```
Analysis exception processing SPDX file: Missing document namespace
```

**Comment by goneall** [comment]
@rnjudge I just tried the latest version of verify with https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXJSONExample-v2.2.spdx.json and it showed no errors.  If you could upload the document causing the problems, I'll take a look.

**Comment by rnjudge** [comment]
@goneall I also can get the document you shared to validate but the same file on `master` branch does not: https://github.com/spdx/spdx-spec/blob/master/examples/SPDXJSONExample-v2.2.spdx.json

I will try to take a look to see what differs between the two branch versions. If you have time to look, my test file that I am trying to validate is uploaded in my second comment above :) (titled output-spdx-json.txt)

**Comment by rnjudge** [comment]
@goneall the issue with the example document on `master` is the leading `Document` dictionary that encapsulates the rest of the document. i.e.:

```
{
  "Document" : {
    "SPDXID" : "SPDXRef-DOCUMENT",
    "spdxVersion" : "SPDX-2.2",
```

Since I was working off of this example to create JSON documents for Tern, that is also the issue I was having. Would you agree this is worth correcting on master? If so, I can open a PR.

**Comment by goneall** [comment]
> Since I was working off of this example to create JSON documents for Tern, that is also the issue I was having. Would you agree this is worth correcting on master? If so, I can open a PR.

@rnjudge Yes - please go ahead and open a PR for master.  I recall an issue raised on the example where the encapsulating document should be removed.  It was probably fixed in the development/2.2.1 branch but not the Master branch.

**Comment by rnjudge** [comment]
Hi @goneall One more question for you... I am trying to validate a document and it says:

```
Analysis exception processing SPDX file: Invalid license expression.  Expecting more operands.
```

Any idea how I know which line number of the file or which part of the document this is referring to? Since my document does not provide any `'licenseConcluded` values for files, I'm unsure which license expression it could be referring to.

**Comment by goneall** [comment]
@rnjudge Normally, when there is a validation error it reports the name of the file, package or other element it found the error in.  If this is all the information produced, it looks like it isn't providing that information here.

I would like for any `licenseConcluded` or `licenseDeclared` fields which contain an `AND`, `OR`, or `WITH`.  The error indicates a binary operator where only one operand was found.

**Comment by rnjudge** [comment]
@goneall hmm, no `WITH`, `AND` or `OR` in the document anywhere... any other ideas?

**Comment by rnjudge** [comment]
Could it be an issue with the `licenseInfoFromFiles`? Should I be using AND instead of a list?

```
      "licenseInfoFromFiles": [
        "Other Permissive Licenses",
        "LGPL 2.1 or later",
        "Sleepycat License",
        "Public Domain",
        "GPL 3.0",
        "GPL 2.0",
        "Apache 2.0",
        "MIT With Modification Obligations",
        "GPL 1.0 or later",
        "LGPL 3.0 or later",
        "BSD-3-Clause",
        "cURL License",
        "LGPL 2.0",
        "BSD Zero Clause License",
        "GFDL 1.3 or later",
        "MIT License",
        "Free unknown",
        "MPL 2.0",
        "FSF All Permissive License",
        "LGPL 2.1",
        "GFDL 1.3",
        "unknown",
        "GPL 3.0 or later",
        "Proprietary License",
        "GFDL 1.1 or later",
        "LGPL 2.0 or later",
        "GPL 2.0 or later"
      ]

```


Another thought was perhaps the `licenseDeclared` license ref having a dash is causing an issue?
```
      "licenseDeclared": "LicenseRef-92fe666",
```

**Comment by goneall** [comment]
From looking at the above, the issue is the spaces in the license ID's.  For example:

`"GPL 3.0 or later",` -> `"GPL-3.0-or-later"`.

The list is fine, it just needs to be a license expression within the list which is restricted to license ID's and operands.

When the parse sees the space, it is expecting an operand.

**Comment by rnjudge** [comment]
Thanks Gary! I will replace the spaces with dashes for each license in that list.

**Comment by rnjudge** [comment]
@goneall I updated the `licenseInfoFromFiles` to the following but am still getting the same `Analysis exception processing SPDX file: Invalid license expression.  Expecting more operands.` error. Any idea how I can get the tool to tell me the line it is complaining about?

```
      "licenseInfoFromFiles": [
        "LGPL-2.0-or-later",
        "LGPL-3.0-or-later",
        "MPL-2.0",
        "GFDL-1.3",
        "MIT-With-Modification-Obligations",
        "GFDL-1.3-or-later",
        "LGPL-2.0",
        "Sleepycat-License",
        "unknown",
        "FSF-All-Permissive-License",
        "GPL-2.0",
        "LGPL-2.1-or-later",
        "Other-Permissive-Licenses",
        "BSD-Zero-Clause-License",
        "BSD-3-Clause",
        "Public-Domain",
        "GPL-3.0-or-later",
        "Proprietary-License",
        "GPL-3.0",
        "LGPL-2.1",
        "Free-unknown",
        "GPL-1.0-or-later",
        "GFDL-1.1-or-later",
        "Apache-2.0",
        "MIT-License",
        "GPL-2.0-or-later",
        "cURL-License"
      ]
```

**Comment by goneall** [comment]
@rnjudge If you want to attach the JSON file, I'll take a look at it later today.

**Comment by rnjudge** [comment]
Thanks @goneall, I have attached the JSON file. 
[scancode.json.txt](https://github.com/spdx/tools-java/files/5810668/scancode.json.txt)

Another thought I had was perhaps I am not listing `licenseInfoInFiles` properly when it does not exist?
```
"licenseInfoInFiles": [
        "NONE"
      ]
```
Does that look right to you? or should `NONE` be outside the list?

**Comment by rnjudge** [comment]
@goneall I think I found the issue... more spaces in the licenses. Will switch here to using the LicenseRef.
```
      "licenseInfoInFiles": [
        "Public Domain"
      ],
```

**Comment by goneall** [comment]
> Does that look right to you? or should NONE be outside the list?

Yes - You should be able to use None here.

> I think I found the issue... more spaces in the licenses. 

I just found the same thing - looks like they are all in the licenseInfoInFiles.

I'm going to create a PR to provide more information in the error message.

**Comment by rnjudge** [comment]
Closing this issue as it is resolved now. Thanks @goneall for your quick responses and helping to get this resolved.

**Comment by rnjudge** [comment]
@goneall I apologize, but still have another question about errors I am seeing with no line numbers... I get `Analysis exception processing SPDX file: Could not find enum constants for  property fileTypes` but all of my `fileTypes` look like this (some are SOURCE and some are BINARY, too)
```
      "fileTypes": [
        "TEXT"
      ],

```
TEXT/SOURCE/BINARY are all acceptable enum constants according to the spec. What's the issue?

**Comment by goneall** [comment]
@rnjudge Can you upload the file with the errors?  I'll look into it.

**Comment by rnjudge** [comment]
@goneall thanks for taking a look. 
[scancode.json.txt](https://github.com/spdx/tools-java/files/5818406/scancode.json.txt)

**Comment by goneall** [comment]
The problem is at line 352,604 (whew!) where there is an empty array of file types:

```
      "fileName": ".gitignore",
      "SPDXID": "SPDXRef-2f4ca63",
      "fileTypes": [
        ""
      ],
```

BTW - the recent PR to improve the error messages helps a lot to track this down - it produced the following message:
`Analysis exception processing SPDX file: Error parsing JSON field for ID SPDXRef-2f4ca63: Could not find enum constants for  property fileTypes`

I'm waiting on a couple other fixes in progress before spinning another release with the error message improvements.

**Comment by rnjudge** [comment]
@goneall thank you for catching that! I agree the improved error message will make a world of difference. I will stop bothering you now ;)

**Comment by goneall** [comment]
@rnjudge No worries :)  It's been helpful to identify the issues in the error handling.
