### ISSUE TITLE
README.md convert example needs to be updated

### ISSUE THREAD

**Issue by riyenas0925** [spdx/tools-java#33]
Hello
First of all, thank you for making a good tool.

* java-tools supports conversion to json and yaml, but it is not shown in README.md
* In the spdx format converters section of the readme.md file, we checked that the example was different from the actual one.
  AS-IS : `java -jar spdx-tools-jar-with-dependencies.jar TagToRDF Examples/SPDXTagExample.tag TagToRDF.rdf`
  TO-BE : `java -jar spdx-tools-jar-with-dependencies.jar Convert Examples/SPDXTagExample.tag TagToRDF.rdf`

#### reference
```
Usage: java -jar spdx-tools-jar-with-dependencies.jar <function> <parameters>
function                 parameter                         example
-------------------------------------------------------------------------------------------------------------------
Convert         inputFile outputFile [fromType] [toType]   Examples/SPDXTagExample.tag TagToSpreadsheet.xls
SPDXViewer      inputFile                                  TestFiles/SPDXRdfExample.rdf
Verify          inputFile [type]                           TestFiles/SPDXRdfExample.rdf
CompareDocs     output.xlsx doc1 doc2 ... docN
GenerateVerificationCode sourceDirectory
Version
MatchingStandardLicenses licenseTextFile
```

can I contribute by revising README.md and sending pr?

Thank you!

**Comment by goneall** [comment]
@riyenas0925 - Good catch on the documentation.

Yes - please go ahead and submit a PR.

Thanks!

**Comment by riyenas0925** [comment]
Dear @goneall 
pr requested :smile: 
please let me know if there is anything I need to change
