### ISSUE TITLE
Download Location regex error

### ISSUE THREAD

**Issue by riyenas0925** [spdx/tools-java#38]
### Describe the bug
If the download location is http://www.google.com, error when converting SPDX.

```
Caused by: org.spdx.library.InvalidSPDXAnalysisException: Invalid download location pattern http://www.google.com. Must match the pattern ^(NONE|NOASSERTION|(((git|hg|svn|bzr)\+)?(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|ssh:\/\/|git:\/\/|svn:\/\/|sftp:\/\/|ftp:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+){0,100}\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*))|(git\+git@[a-zA-Z0-9\.]+:[a-zA-Z0-9/\\.@]+)|(bzr\+lp:[a-zA-Z0-9\.]+))$
web_1  | 	at org.spdx.library.model.SpdxPackage.setDownloadLocation(SpdxPackage.java:239)
web_1  | 	at org.spdx.library.model.SpdxPackage.<init>(SpdxPackage.java:111)
web_1  | 	at org.spdx.library.model.SpdxPackage$SpdxPackageBuilder.build(SpdxPackage.java:1036)
web_1  | 	at org.spdx.spreadsheetstore.PackageInfoSheetV2d2.getPackage(PackageInfoSheetV2d2.java:550)
web_1  | 	... 81 common frames omitted
```

### SPDX Download location Specification
IMHO, the spec doesn't seem to say that a trailing slash is mandatory. 
* https://spdx.github.io/spdx-spec/package-information/#771-description
```
In VCS location compact notations, 
the trailing slashes in <host_name>, <path_to_repository> are not significant. 
Leading and trailing slashes in <sub_path> are not significant.
```

### download location regular expression
This is the download location regular expression currently used by spdx-tools-java.
```
^(NONE|NOASSERTION|(((git|hg|svn|bzr)\+)?(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/|ssh:\/\/|git:\/\/|svn:\/\/|sftp:\/\/|ftp:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+){0,100}\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*))|(git\+git@[a-zA-Z0-9\.]+:[a-zA-Z0-9/\\.@]+)|(bzr\+lp:[a-zA-Z0-9\.]+))$
```

**Comment by goneall** [comment]
@riyenas0925 I tend to agree with your assessment.

Would you like to create a PR to fix this or paste a corrected regex in this issue?

**Comment by riyenas0925** [comment]
I will make a pr and contribute. 😄

**Comment by riyenas0925** [comment]
@goneall 
I finished pr :smile_cat: 
If the issue becomes merge, when will it be released?

**Comment by goneall** [comment]
> If the issue becomes merge, when will it be released?

I was planning a new release of the tools-java within the next week or two - before the next release of the SPDX license list.
