### ISSUE TITLE
[Question] About the error message "ERROR StatusLogger No log4j2 configuration file found"

### ISSUE THREAD

**Issue by shi9qiu** [spdx/tools-java#43]
When I try to use this library to convert the format of the SPDX file, I get the following error message:

`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.`

I wonder does anyone know the reason or see the same message?

The command I executed is:

`java -jar tools-java-1.0.3-jar-with-dependencies.jar Convert SPDXJSONExample-v2.2.spdx.json SPDXJSONExample-v2.2.spdx.rdf`

Thanks!

**Comment by goneall** [comment]
> I wonder does anyone know the reason or see the same message?

I also get this message on every run.  I think you can safely ignore it.

It would be nice to get rid of the message, however.  Let me know if you have any ideas on the cause or resolution.

**Comment by shi9qiu** [comment]
>I also get this message on every run. I think you can safely ignore it.
It would be nice to get rid of the message, however. Let me know if you have any ideas on the cause or resolution.

Thank you for your response! I will share if I find out something new about this error message.
