### ISSUE TITLE
Is there any function for get all SpdxPackage?

### ISSUE THREAD

**Issue by nam-np** [spdx/tools-java#48]
I used function `deserializeDocument` for creating `SpdxDocument` from RDF file.
https://github.com/spdx/tools-java/blob/d9c128f0d8fea4c1710893ed662a3b64080998c7/src/main/java/org/spdx/tools/SpdxToolsHelper.java#L144
 And now I want to get all SpdxPackage similar with function `findAllPackages` in **tools** library:
https://github.com/spdx/tools/blob/d5c23fd9fe47f6732239764204f27d1edae6eb94/src/org/spdx/rdfparser/SpdxDocumentContainer.java#L714

In this **tools-java** library have any function can support?

**Comment by goneall** [comment]
You can call [getElements](https://github.com/spdx/Spdx-Java-Library/blob/a22ea13c3356b68151146b87be843a2b741bce57/src/main/java/org/spdx/library/model/SpdxModelFactory.java#L245) passing in the `SpdxPackage.class` as the spdxClass.  It will return a Java stream of SpdxPackages.  

You can find an example in [CommonCode.java](https://github.com/spdx/spdx-java-tagvalue-store/blob/5c7435d88bfdbcbfa22d1b6572650ddf2a296df5/src/main/java/org/spdx/tag/CommonCode.java#L161).

**Comment by goneall** [comment]
Close this issue as resolved.
