### ISSUE TITLE
Change deployments from Bintray to Maven Central and Github packages

### ISSUE THREAD

**Issue by goneall** [spdx/tools-java#5]
Bintray is retiring their service on May 1.  Prior to retirement, we need to start publishing an alternative package storage provider.

Suggest both Maven Central and Github Packages.

This can be automated using Github actions.  See https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository-and-github-packages

**Comment by NicolasToussaint** [comment]
And now, the link to bintray in the Readme doc points to a a 404: https://bintray.com/spdx/spdx-tools/tools-java

**Comment by goneall** [comment]
@NicolasToussaint Thanks for pointing this out - completely forgot to update the REAMDE when bintray went away.

I'll create a PR later this week to fix.

**Comment by goneall** [comment]
Resolve with PR #18 and PR #17
