### ISSUE TITLE
Checksum for release artifacts

### ISSUE THREAD

**Issue by Jeeppler** [spdx/tools-java#52]
## Short Description

Please provide a checksum for the release artifacts.

## **Describe the Update**

Provide a checksum of the release artifacts. 

## **How This Feature will help you/your organization**

It allows one to confirm the integrity of the downloaded file. A simple checksum does not provide authenticity, but at least let's one verify the integrity.

## **Possible Solution/Implementation Details**

Use SHA-2 e.g. SHA256 and add the output of the Linux utility sha256sum as file.

~~~
sha256sum  tools-java-1.0.4.zip >  tools-java-1.0.4.zip.sha256sum
~~~

In release section: 

*  tools-java-1.0.4.zip
*  tools-java-1.0.4.zip.sha256sum

## **Example & Links**

Both LinuxMint and Qubes OS provide checksums and signed checksums for their release artifacts (ISO files).

- [How to Verify a Linux ISO’s Checksum and Confirm It Hasn’t Been Tampered With](https://www.howtogeek.com/246332/how-to-verify-a-downloaded-linux-iso-file-wasnt-tampered-with/)](https://www.howtogeek.com/246332/how-to-verify-a-downloaded-linux-iso-file-wasnt-tampered-with/)
- [Linux Mint 20.3 "Una" - Download Cinnamon](https://linuxmint.com/edition.php?id=292)
- [Verifying signatures](https://www.qubes-os.org/security/verifying-signatures/)

**Comment by goneall** [comment]
Added a sha256 checksum per suggestion above

**Comment by Jeeppler** [comment]
@goneall thank you.
