### ISSUE TITLE
Converting Tag file to RDF exception: NoSuchMethodError

### ISSUE THREAD

**Issue by chris-no1** [spdx/tools-java#61]
I am getting an exception `NoSuchMethodError` when to convert a tag file to an RDF file by using the `TagToRDF` class by the `convertTagFileToRdf` function..

I am using the test file _tools-java/testResources/SPDXTagExample-v2.2.spdx_ from the Github repo. Loading the tag example file works fine and logging the annotations from the file by using the `SpdxElement` and `Annotation` classes. The exception is thrown when converting the tag file to RDF, when the function sets behavior by creating a new BuildDocument class. None of the input parameters are null.

Exception
```
org.spdx.tag.BuildDocument.<init>([Lorg/spdx/rdfparser/SpdxDocumentContainer;Ljava/util/Properties;Ljava/util/List;)V
java.lang.NoSuchMethodError
    at org.clearbyte.persistance.test.SpdxManagerTest.spdxTagFileToRDFTest(SpdxManagerTest.java:61)
```
TagToRdf class
```
public static SpdxDocumentContainer convertTagFileToRdf(InputStream spdxTagFile, String outputFormat, List<String> warnings) throws RecognitionException, TokenStreamException,InvalidSpdxTagFileException,InvalidFileFormatException, Exception  {
…
HandBuiltParser parser = new HandBuiltParser(nci);
SpdxDocumentContainer[] result = new SpdxDocumentContainer[1];
parser.setBehavior(new BuildDocument(result, constants, warnings));
parser.data();
```
My code
```
public void convertSpdxTagFileToTurtleRdf(InputStream spdxTagFile, OutputStream outputTurtleRdf) {
        List<String> warnings = new ArrayList<>();
        try {
            TagToRDF.convertTagFileToRdf(spdxTagFile, outputTurtleRdf, "TURTLE", warnings);
        } catch (Exception ex) {
            warnings.stream().forEach(x -> log.debug(x));
            log.debug(ex.getLocalizedMessage());            
        }
    }
```
Included libs
```
<dependency>
            <groupId>org.spdx</groupId>
            <artifactId>java-spdx-library</artifactId>
            <version>1.0.10</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.spdx</groupId>
            <artifactId>spdx-jackson-store</artifactId>
            <version>1.0.4</version>
        </dependency> 
        <dependency>
            <groupId>org.spdx</groupId>
            <artifactId>spdx-rdf-store</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.spdx</groupId>
            <artifactId>spdx-tagvalue-store</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.spdx</groupId>
            <artifactId>spdx-tools</artifactId>
            <version>2.2.7</version>
        </dependency>
```
I am including the spdx-tools-2.2.7.jar and using Java 11. I haven’t been able to try Java 8 since my project will only accept version 11 or higher. And I didn't find documentation for the intended java version for the /spdx/[tools-java](https://github.com/spdx/tools-java/tree/05afeed90703f0579c4149e612004beac61eca7e).

**Comment by chris-no1** [comment]
I can try to solve it, but haven't forked and built `/tool-java` yet.

**Comment by chris-no1** [comment]
Tanks Gary. 

Is the `pdx-tools` included in the java-tools for backward compatibility or does it has other purposes?

**Comment by goneall** [comment]
> Is the spdx-tools included in the java-tools for backward compatibility or does it has other purposes?

Just for compatibility as far as I know

**Comment by goneall** [comment]
Closing this issue as resolved.
