### ISSUE TITLE
Compare tool removes common part of filename

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-java#67]
This behavior may be intended (if so, ignore...), but I was pretty confused by it when trying out the tools, so I wanted to bring it up anyway.

I ran the following command to compare two of the example documents:
```
$ java -jar tools-java-1.1.0-jar-with-dependencies.jar CompareDocs compareOutput.xlsx ../testResources/SPDXJSONExample-v2.2.spdx.json ../testResources/SPDXJSONExample-v2.3.spdx.json
```
In the resulting spreadsheet, the two names were shown as `2.spdx.json` and `3.spdx.json`; the common part in the beginning was most likely trimmed by the [normalizeDocNames](https://github.com/spdx/tools-java/blob/6eea344a264c908146d6105c8647637f5e27bb08/src/main/java/org/spdx/tools/CompareSpdxDocs.java#L165) function.

**Comment by goneall** [comment]
@nicoweidner - It's been a while, but I don't think this is intentional.  It would be better to just remove the common portions of the path before the filename.
