### ISSUE TITLE
Compare tool lists package in multiple files if it is present in only one

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-java#69]
As part of some experiments, I compared two JSON files:
```
$ java -jar tools-java-1.1.0-jar-with-dependencies.jar CompareDocs compareOutput.xlsx ../testResources/SPDXJSONExample-v2.2.spdx.json ../testResources/SPDXJSONExample-v2.3.spdx.json
```
In order to understand the output better, I tried to remove a package from either of the files and check what changed in the output. I removed this section from either of the two json files:
```
{
    "SPDXID" : "SPDXRef-fromDoap-1",
    "copyrightText" : "NOASSERTION",
    "downloadLocation" : "NOASSERTION",
    "filesAnalyzed" : false,
    "homepage" : "http://commons.apache.org/proper/commons-lang/",
    "licenseConcluded" : "NOASSERTION",
    "licenseDeclared" : "NOASSERTION",
    "name" : "Apache Commons Lang"
  }, 
```
The observed result was:
- The output was unchanged if the package was removed from only one of the two input files. The package `SPDXRef-fromDoap-1` was still shown in both columns
- When removed from both input files, the package vanished from both columns (as expected)

I would have expected no output in the v2.2 column concerning package `SPDXRef-fromDoap-1` after removing it from the v2.2 file.

**Comment by goneall** [comment]
@nicoweidner Thanks for the analysis - definitely sounds like a bug.

**Comment by goneall** [comment]
@nicoweidner This is likely due to the duplicate namespaces in the two compare documents.  If you could change one of the namespaces and see if it displays correctly.

PR #70 adds a check to fail any compare with duplicate namespace.

**Comment by nicoweidner** [comment]
That does indeed resolve it, thanks for looking into this!

The created spreadsheet now shows `[No Package]` in the column where the package was removed - with one exception: the line `Attributions` is empty. Doesn't seem that important, though.
