### ISSUE TITLE
Verify should support file extension "yml"

### ISSUE THREAD

**Issue by neubs-bsi** [spdx/tools-java#8]
When running `Verify` with a SPDX file that is in the yaml format, but has the file extension `yml` as opposed to `yaml` I get the following error:
`Invalid file name: project.spdx.yml`

This error stems from a check in the verifier [1] where the file extension gets checked against a list of possible file extensions [2], which doesn't contain the extension `yml`
According to the format requirements [3] 1.7.8: `YAML -> *.spdx.yaml or *.spdx.yml` `yml` should be supported.

[1] https://github.com/spdx/tools-java/blob/abf35254f765d37b6767fef120e5c9de687a2573/src/main/java/org/spdx/tools/Verify.java#L76
[2] https://github.com/spdx/tools-java/blob/abf35254f765d37b6767fef120e5c9de687a2573/src/main/java/org/spdx/tools/SpdxToolsHelper.java#L64
[3] https://spdx.github.io/spdx-spec/1-rationale/#17-format-requirements

**Comment by goneall** [comment]
@neubs-bsi Agreed - do you mind going ahead and adding a PR with the change?

**Comment by neubs-bsi** [comment]
Hello @goneall

I would like to contribute, but am currently unable to, since our company internal contribution process for the tools-java project is not finished yet. 

The change isn't a big one, so if there's no hurry, I would be happy to contribute once our internal contribution process is finished.

**Comment by goneall** [comment]
@neubs-bsi No worries - I'll make the change next time I'm in the code for this project.

**Comment by ek08** [comment]
@goneall should I make a PR for this?

**Comment by goneall** [comment]
@ek08 Yes - please make a PR for this.

**Comment by goneall** [comment]
Resolved with PR #9
