### ISSUE TITLE
Version output error?

### ISSUE THREAD

**Issue by pjsnps** [spdx/tools-java#94]
See below: doc bug, "1.0.5" should be "1.1.4" or so?

cd dev/hub/spdx/
git clone https://github.com/spdx/tools-java.git
cd tools-java/
less README.md
mvn clean install # failed for missing javadoc executable
vi pom.xml # removed lines with javadoc; there's probably a smarter way...
mvn clean install
java -jar ./target/tools-java-1.1.4-SNAPSHOT-jar-with-dependencies.jar help
#In BLACK DUCKv2022.10.0, generate sbom for openssl

java -jar ./target/tools-java-**1.1.4**-SNAPSHOT-jar-with-dependencies.jar Version
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
SPDX Tool Version: **1.0.5**; Specification Version: SPDX-2.3; License List Version: 3.18
^doc bug, "1.0.5" should be "1.1.4" or so?

java -jar ./target/tools-java-1.1.4-SNAPSHOT-jar-with-dependencies.jar Verify ../sbom_2022-11-11_155108.spdx.json
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
This SPDX Document is valid.

**Comment by goneall** [comment]
Thanks @pjsnps for pointing this out.

I was updating the version in the library, but apparently not updating the version for the tools on release.

I'll create a PR to fix for this version.
