### ISSUE TITLE
Option of using SPDX ID URI when converting tag files - Change proposal

### ISSUE THREAD

**Issue by chris-no1** [spdx/tools-java#97]
When using the SpdxConverter class (Java API) or the Convert (command line) to convert from SPDX tag file format to RDF the function includes the full licence text which makes the RDF file verbose for further processing.

The proposal is to add an option to function _--excludeLicenseDetails_ to include a URI with a prefix (/licences/) to the licence SPDX-License-Identifier instead insert the full text in the destination file. Example URI: http://spdx.org/licenses/GPL-2.0-or-later. Alternatively to make the default behaviour to include the licence URI and use _--includeLicenseDetails_ as an option, but that could maybe cause consequences?

**Comment by goneall** [comment]
> Alternatively to make the default behaviour to include the licence URI and use --includeLicenseDetails as an option, but that could maybe cause consequences

I would prefer the _--excludeLicenseDetails_ for compatibility reasons.

I'll add a related issue to the [spdx-java-rdf-store](https://github.com/spdx/spdx-java-rdf-store) repo which will be a dependency for this fix.
